/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v -c AutopilotAdaptor -a src/dbus_adaptor.h:src/dbus_adaptor.cpp src/dbus_spec.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "src/dbus_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

#include <QDebug>

/*
 * Implementation of adaptor class AutopilotAdaptor
 */

AutopilotAdaptor::AutopilotAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

AutopilotAdaptor::~AutopilotAdaptor()
{
    // destructor
}

QList<QVariantMap> AutopilotAdaptor::GetState(const QString &piece)
{
    // handle method call com.canonical.Unity.Debug.Introspection.GetState
    // QList<QVariantMap> state;
    // QMetaObject::invokeMethod(parent(),
    //     "GetState",
    //     Q_RETURN_ARG(QList<QVariantMap>, state),
    //     Q_ARG(QString, piece));

    // qDebug() << "Wrapper returning state:" << state << "query was:" << piece;
    // return state;
    QList<QVariantMap> state;
    qDebug() << "Inside GetState()";
    QVariantMap m;
    m["some_property"] = QString("Some Value");
    state.append(m);
    return state;
}

